name: Deploy Databricks Notebooks

on:
  push:
    branches:
      - main   # Change branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Databricks CLI
      - name: Install Databricks CLI
        run: pip install databricks-cli --upgrade
        env:
          DATABRICKS_HOST: https://dbc-e380e487-14e8.cloud.databricks.com/
          DATABRICKS_TOKEN: ${{ secrets.DB_token }}

      # Step 3: Ensure workspace folders exist
      - name: Create Databricks workspace folders
        run: |
          databricks workspace mkdirs $WORKSPACE_PATH/Bronze
          databricks workspace mkdirs $WORKSPACE_PATH/Silver
          databricks workspace mkdirs $WORKSPACE_PATH/Gold
          databricks workspace mkdirs $WORKSPACE_PATH/Utils
        env:
          DATABRICKS_HOST: https://dbc-e380e487-14e8.cloud.databricks.com/
          DATABRICKS_TOKEN: ${{ secrets.DB_token }}
          WORKSPACE_PATH: /Workspace/Users/ansarivahid547@gmail.com/Dev

      # Step 4: Delete old content (optional clean-up)
      - name: Clean Databricks workspace folders
        run: |
          databricks workspace delete -r $WORKSPACE_PATH/Bronze || true
          databricks workspace delete -r $WORKSPACE_PATH/Silver || true
          databricks workspace delete -r $WORKSPACE_PATH/Gold   || true
          databricks workspace delete -r $WORKSPACE_PATH/Utils  || true

          databricks workspace mkdirs $WORKSPACE_PATH/Bronze
          databricks workspace mkdirs $WORKSPACE_PATH/Silver
          databricks workspace mkdirs $WORKSPACE_PATH/Gold
          databricks workspace mkdirs $WORKSPACE_PATH/Utils
        env:
          DATABRICKS_HOST: https://dbc-e380e487-14e8.cloud.databricks.com/
          DATABRICKS_TOKEN: ${{ secrets.DB_token }}
          WORKSPACE_PATH: /Workspace/Users/ansarivahid547@gmail.com/Dev

      # Step 5: Import fresh notebooks
      - name: Import notebooks into Databricks
        run: |
          databricks workspace import-dir citibike_etl/notebooks/bronze $WORKSPACE_PATH/Bronze
          databricks workspace import-dir citibike_etl/notebooks/silver $WORKSPACE_PATH/Silver
          databricks workspace import-dir citibike_etl/notebooks/gold   $WORKSPACE_PATH/Gold
          databricks workspace import-dir citibike_etl/notebooks/utils  $WORKSPACE_PATH/Utils
        env:
          DATABRICKS_HOST: https://dbc-e380e487-14e8.cloud.databricks.com/
          DATABRICKS_TOKEN: ${{ secrets.DB_token }}
          WORKSPACE_PATH: /Workspace/Users/ansarivahid547@gmail.com/Dev


# name: CD Workflow

# on:
#   push:
#     branches:
#       - main

# jobs:
#   cd-deploy-dev:
#     name: Deploy to DEV
#     runs-on: ubuntu-latest
#     environment: dev
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Setup Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.11'

#       - name: Install Databricks CLI
#         run: curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

#       - name: Install Dependencies
#         run: |
#           pip install --upgrade pip
#           pip install setuptools wheel

#       - name: Configure Databricks
#         run: |
#           # write out the profile (here called "TEST")
#           cat <<EOF > ~/.databrickscfg
#           [DEFAULT]
#             host  = https://dbc-e380e487-14e8.cloud.databricks.com/
#             token = ${{ secrets.DB_token }}
#           EOF

#       - name: Deploy to DEV
#         run: |
#           databricks bundle deploy

#   cd-deploy-test:
#     name: Deploy to TEST
#     runs-on: ubuntu-latest
#     environment: test
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Setup Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.11'

#       - name: Install Databricks CLI
#         run: curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

#       - name: Install Dependencies
#         run: |
#           pip install --upgrade pip
#           pip install setuptools wheel

#       - name: Configure Databricks
#         run: |
#           # write out the profile (here called "TEST")
#           cat <<EOF > ~/.databrickscfg
#           [TEST]
#             host  = https://dbc-ba82de44-d338.cloud.databricks.com/
#             token = ${{ secrets.DB_token_test }}
#           EOF

#       - name: Deploy to TEST
#         run: |
#           databricks bundle deploy --target test --profile TEST
